# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/almanac1631/scrubarr/internal/app/scrubarr.version={{.Version}} -X github.com/almanac1631/scrubarr/internal/app/scrubarr.commit={{.Commit}}'
    goos:
      - 'freebsd'
      - 'windows'
      - 'linux'
      - 'darwin'
    goarch:
      - 'amd64'
      - '386'
      - 'arm'
      - 'arm64'
    ignore:
      - goos: 'darwin'
        goarch: '386'
    main: ./cmd/scrubarr/main.go
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
